async page => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://localhost:4173/?v=hero-videos');
  await page.waitForFunction(()=>{const v=document.querySelector('video');return v.readyState>=2&&v.currentTime>.2&&!v.paused;});
  const read=()=>page.locator('video').evaluate(v=>({src:v.getAttribute('src'),width:v.videoWidth,height:v.videoHeight,muted:v.muted,loop:v.loop,paused:v.paused,currentTime:v.currentTime}));
  const desktop=await read();
  if(desktop.width!==1920||desktop.height!==1080||!desktop.muted||!desktop.loop)throw Error('Desktop video mismatch');
  await page.getByRole('button',{name:'Pausar vídeo',exact:true}).click();
  if(!(await read()).paused)throw Error('Pause failed');
  await page.getByRole('button',{name:'Reproduzir vídeo',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('video').paused);
  await page.screenshot({path:'output/playwright/desktop.png'});
  await page.screenshot({path:'output/playwright/desktop-completa.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  await page.waitForFunction(()=>{const v=document.querySelector('video');return v.videoHeight===1920&&v.currentTime>.2&&!v.paused;});
  const mobile=await read();
  if(mobile.width!==1080||mobile.height!==1920)throw Error('Mobile video mismatch');
  const ratio=await page.locator('.hero-media').evaluate(el=>el.clientWidth/el.clientHeight);
  if(Math.abs(ratio-9/16)>.002)throw Error('Portrait frame mismatch');
  await page.screenshot({path:'output/playwright/mobile.png'});
  await page.screenshot({path:'output/playwright/mobile-completa.png',fullPage:true});
  await page.locator('video').scrollIntoViewIfNeeded();
  await page.screenshot({path:'output/playwright/mobile-video.png'});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>document.querySelector('video').paused);
  if(!(await read()).paused)throw Error('Reduced motion failed');
  await page.reload();
  if(await page.locator('video').getAttribute('src'))throw Error('Reduced motion should not download video automatically');
  await page.locator('.hero-media').scrollIntoViewIfNeeded();
  await page.getByRole('button',{name:'Reproduzir vídeo',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('video').paused&&document.querySelector('video').currentTime>0);
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
  if(await page.locator('.catalog-section,.steps-section,.madame-section,.faq-section').count())throw Error('Removed sections returned');
  if(errors.length)throw Error(JSON.stringify(errors));
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://localhost:4173/?v=hero-videos');
  return {desktop,mobile,portraitRatio:ratio,pauseResume:true,reducedMotion:true,removedSectionsStillAbsent:true,errors};
}
