import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,appendFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createAdminHandler} from '../admin-store.mjs';
import {createLeadHandler} from '../lead-store.mjs';
const directory=await mkdtemp(path.join(os.tmpdir(),'madame-admin-test-'));
const password='Test-only-password-'+randomUUID();
const handler=createAdminHandler(directory,{password});await handler.initialize();
const leads=createLeadHandler(directory);
const server=http.createServer((req,res)=>req.url==='/api/leads'?leads(req,res):handler(req,res));
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
let csrfToken='';
const post=(route,value,cookie='',origin=base)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie,'X-CSRF-Token':csrfToken},body:JSON.stringify(value)});
const get=(route,cookie='')=>fetch(base+route,{headers:{Cookie:cookie}});
try {
  assert.equal((await get('/api/admin/dashboard')).status,401);
  assert.equal((await get('/api/admin/export')).status,401);
  assert.equal((await post('/api/admin/login',{password},'','https://outside.test')).status,403);
  assert.equal((await post('/api/admin/login',{password:'wrong'})).status,401);
  const login=await post('/api/admin/login',{password});assert.equal(login.status,200);
  csrfToken=(await login.json()).csrfToken;
  const cookie=login.headers.get('set-cookie').split(';')[0];
  assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  assert.equal((await get('/api/admin/session',cookie)).status,200);
  let data=await (await get('/api/admin/dashboard',cookie)).json();assert.equal(data.totalLeads,0);assert.equal(data.sessions,0);
  const attribution={sessionId:randomUUID(),source:'instagram',medium:'social',campaign:'lancamento',referrer:'https://instagram.com/?private=secret',device:'mobile'};
  const event={id:randomUUID(),type:'pageview',attribution};
  assert.equal((await post('/api/track',event)).status,201);
  assert.equal((await post('/api/track',event)).status,200);
  await post('/api/track',{...event,id:randomUUID()});
  await post('/api/track',{...event,id:randomUUID(),type:'checkout'});
  assert.equal((await post('/api/track',{...event,id:randomUUID(),type:'purchase'})).status,400);
  const lead={name:'=Teste de fórmula',email:'teste@example.com',phone:'11999990000',consent:true,attribution,qualification:{revenueRange:'10k-to-100k',personType:'pj'}};
  assert.equal((await post('/api/leads',lead)).status,201);
  await appendFile(path.join(directory,'leads.jsonl'),JSON.stringify({id:randomUUID(),createdAt:new Date().toISOString(),name:'Cadastro anterior',email:'anterior@example.com',phone:'+5511999991111',consent:true})+'\n');
  data=await (await get('/api/admin/dashboard',cookie)).json();
  assert.equal(data.views,2);assert.equal(data.sessions,1);assert.equal(data.clicks,1);assert.equal(data.totalLeads,2);assert.equal(data.conversion,100);assert.equal(data.unattributed,1);
  assert.equal(data.sources.find(s=>s.name==='instagram').leads,1);
  assert.equal(data.leads.find(l=>l.email===lead.email).attribution.referrer,'instagram.com');
  data=await (await get('/api/admin/dashboard?source=instagram&campaign=lancamento&q=teste',cookie)).json();
  assert.equal(data.matched,1);assert.equal(data.totalLeads,1);
  const qualified=await (await get('/api/admin/dashboard?businessSize=M%C3%A9dio&personType=pj',cookie)).json();assert.equal(qualified.matched,1);assert.equal(qualified.leads[0].qualification.revenueRange,'10k-to-100k');
  const unmatched=await (await get('/api/admin/dashboard?businessSize=Grande',cookie)).json();assert.equal(unmatched.matched,0);assert.equal(unmatched.totalLeads,2);
  const csv=await get('/api/admin/export?q=teste',cookie);assert.equal(csv.status,200);assert.match(await csv.text(),/"'=Teste de fórmula"/);
  assert.equal((await get('/api/admin/dashboard?from=2020-01-01&to=2026-12-31',cookie)).status,400);
  const traffic=await readFile(path.join(directory,'traffic.jsonl'),'utf8');assert.ok(!traffic.includes('private=secret'));assert.ok(!traffic.includes('remoteAddress'));
  const nextPassword='Changed-password-'+randomUUID();
  assert.equal((await post('/api/admin/password',{current:password,password:nextPassword},cookie)).status,200);
  assert.equal((await get('/api/admin/session',cookie)).status,401);
  assert.equal((await post('/api/admin/login',{password})).status,401);
  const nextLogin=await post('/api/admin/login',{password:nextPassword});assert.equal(nextLogin.status,200);
  csrfToken=(await nextLogin.json()).csrfToken;
  const nextCookie=nextLogin.headers.get('set-cookie').split(';')[0];
  await post('/api/admin/logout',{},nextCookie);assert.equal((await get('/api/admin/session',nextCookie)).status,401);
  const reloaded=createAdminHandler(directory);await reloaded.initialize();
  assert.ok(!(await readFile(path.join(directory,'admin-auth.json'),'utf8')).includes(nextPassword));
  for(let i=0;i<8;i++)await post('/api/admin/login',{password:'wrong'});
  assert.equal((await post('/api/admin/login',{password:nextPassword})).status,429);
  console.log('PASS: authentication, origin, protected exports, empty store, attribution, deduplication, legacy leads, filters, CSV safety, password rotation, logout and rate limit.');
} finally {
  await new Promise(resolve=>server.close(resolve));
  await rm(directory,{recursive:true,force:true});
}
