from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'public/index.html'
text=p.read_text(encoding='utf-8')
text=text.replace('  <link rel="preload" href="assets/sans.woff" as="font" type="font/woff" crossorigin>','')
text=text.replace('<script defer src="app.js"></script>','<script defer src="config.js"></script>\n  <script defer src="app.js"></script>')
text=text.replace('<p class="hero-lead">Você escolhe o que vender.<br>A Madame mostra onde procurar.</p>','')
text=text.replace('20 listas digitais para explorar fornecedores,<br class="desktop-break"> consultar informações e começar sua pesquisa.','Explore 20 listas digitais organizadas por segmento e encontre caminhos para pesquisar fornecedores para o seu negócio.')
text=text.replace('Quero explorar as listas','Conhecer as listas')
text=text.replace('<div class="hero-seal"','<img class="hero-portrait" src="assets/madame.webp" width="850" height="1140" alt="Madame de blazer rosa, personagem da marca" fetchpriority="high">\n        <div class="hero-seal"')
text=text.replace('O olhar de quem ama garimpar.','Um convite para descobrir.')
text=text.replace('A Mina de Fornecedores reúne listas por assunto para você organizar a busca, conhecer opções e iniciar suas cotações.','Contatos soltos, abas abertas e informações espalhadas tornam a pesquisa mais trabalhosa. A coleção reúne 20 listas por assunto para você organizar a busca, conhecer opções e iniciar suas cotações.')
text=text.replace('<div class="catalog-grid" id="catalog-grid"></div>','<div class="catalog-grid" id="catalog-grid">\n<!-- CATALOG_START -->\n<!-- CATALOG_END -->\n</div>')
text=text.replace('Uma área de membros para encontrar o assunto que faz sentido para você e acessar os materiais da coleção.','Conheça a organização por assunto nesta demonstração visual da coleção. Escolha um segmento para entender a proposta dos materiais.')
text=text.replace('<figure class="platform-figure reveal">','<figure class="platform-figure reveal">\n          <span class="demo-label">DEMONSTRAÇÃO ILUSTRATIVA</span>')
text=text.replace('Uma visão das coleções disponíveis na área de membros.','Representação ilustrativa da organização das listas. Não é uma captura da área de membros nem uma prévia de suas funcionalidades.')
text=text.replace('Na área de membros, abra a lista relacionada aos produtos que você quer pesquisar.','Escolha o segmento relacionado aos produtos que você quer pesquisar.')
text=text.replace('Madame <em>Fulô</em>','Madame')
text=text.replace('Quem acompanha a Madame conhece essa energia: olhar com atenção e querer descobrir o que vem depois.','A Garimpo da Madame apresenta a Lista de Fornecedores Madame: uma coleção de materiais digitais para apoiar a pesquisa de lojistas, revendedores e de quem quer começar a vender.')
text=text.replace('Agora, esse convite acompanha a sua pesquisa por fornecedores. Escolha o seu segmento e conheça novas opções para a sua revenda.','A personagem Madame dá identidade a esse convite para explorar. Você escolhe o assunto, consulta as informações e dá o próximo passo na sua pesquisa.')
text=text.replace('<button class="button button-pink" id="explore-complete">Quero ver todas as listas <svg><use href="#arrow"/></svg></button>','<div class="offer-terms" id="offer-terms" hidden></div><a class="button button-pink" id="explore-complete" href="#categorias">Quero ver todas as listas <svg><use href="#arrow"/></svg></a>')
text=text.replace('A Lista de Fornecedores Madame é uma oferta própria. Benefícios do Clube só podem ser considerados incluídos quando estiverem expressamente informados na compra.','Não. Esta página apresenta a coleção de 20 listas digitais. Preços e benefícios do Clube do Garimpo não fazem parte desta apresentação.')
text=text.replace('São todos fornecedores de logística reversa?','Para quem são as listas?')
text=text.replace('As listas reúnem perfis diferentes, incluindo fabricantes, importadores e outras empresas. A origem e a condição das mercadorias devem ser confirmadas individualmente.','Para lojistas, revendedores e pessoas que querem começar ou ampliar suas vendas e buscam um ponto de partida para pesquisar fornecedores.')
text=text.replace('<span>Lista digital com links para consulta.</span>','<span>Apresentação da lista · material digital.</span>')
text=text.replace('Os materiais e as condições comerciais disponíveis variam conforme o fornecedor.','Esta demonstração apresenta a capa e o assunto. Os PDFs completos e os contatos não estão disponíveis nesta página pública. Confirme as condições comerciais diretamente com cada fornecedor.')
(root/'template.html').write_text(text,encoding='utf-8')
print('Existing HTML adapted into template.html')
